<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class GeneratedProductionOrdersExport implements FromCollection, WithHeadings
{
    private Collection $rows;

    public function __construct(Collection $rows)
    {
        $this->rows = $rows;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    public function collection()
    {
        return $this->rows;
    }

    public function headings(): array
    {
        return
            [
                'Production Order No', 'Transaction Date', 'Line No', 'Line Type', 'Item No', 'Item Description', 'Quantity', 'UOM', 'Location', 'Bin', 'Routing', 'Process', 'Recipe', 'Step', 'Ext. Document No', 'Batch No', 'Weighed Item', 'Packed Item', 'Net Weight', 'IDT No', 'Published?', 'Generated By', 'Generated At'
            ];
    }
}
